storage:
    databaseUrl: postgres://watchdog:watchdog@watchdog-db:5432/watchdog?sslmode=disable

watchtime:
    monday:     [["07:30:00", "20:30:00"]]
    tuesday:    [["07:30:00", "20:30:00"]]
    wednesday:  [["07:30:00", "20:30:00"]]
    thursday:   [["07:30:00", "20:30:00"]]
    friday:     [["07:30:00", "20:30:00"]]
    saturday:   []
    sunday:     []
